name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Version & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node & PNPM
        uses: ./packages/setup-node-pnpm

      - name: Lint
        run: pnpm lint

      - name: Validate actions
        run: pnpm -r run validate

      - name: Create Release PR or Tag
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: pnpm version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish semantic action refs
        id: publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: bash ./scripts/sync-action-refs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Teams
        if: steps.publish.outputs.published != ''
        uses: ./packages/notify-teams
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
          build-version: ${{ steps.publish.outputs.published }}
